# Generated by Django 3.0.5 on 2020-06-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20200607_1500'),
    ]

    operations = [
    ]
