# Generated by Django 3.0.5 on 2020-06-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20200608_0115'),
    ]

    operations = [
    ]
